name: Issue Notifications

on:
  workflow_dispatch:  # Manual test button
  issues:             # Fires on any issue event
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]
  issue_comment:      # Fires when comment is created, edited, deleted
    types: [created, edited, deleted]

jobs:
  email-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email for Any Issue Event
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          to: ${{ secrets.TO_EMAIL }}
          from: GitHub Issue Bot <${{ secrets.SMTP_USERNAME }}>
          subject: >
            [${{ github.repository }}] Issue Event: ${{ github.event.issue.title }}
          body: |
            Repository: ${{ github.repository }}
            Event: ${{ github.event.action }}
            Actor: ${{ github.event.sender.login }}

            Issue: #${{ github.event.issue.number }} — ${{ github.event.issue.title }}
            Link:  ${{ github.event.issue.html_url }}

            --------
            ${{ github.event.comment.body || 'No comment text available.' }}
