name: Repo Notifications

on:
  workflow_dispatch:
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned, labeled, unlabeled]
  issue_comment:
    types: [created, edited, deleted]
  push:

jobs:
  email-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email for Repo Events
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          to: ${{ secrets.TO_EMAIL }}
          from: Big Mango Tree <${{ secrets.SMTP_USERNAME }}>
          subject: >
            [${{ github.repository }}] Event: ${{ github.event_name }}
          body: |
            Repository: ${{ github.repository }}
            Event: ${{ github.event_name }}
            Actor: ${{ github.event.sender.login }}

            {% if github.event_name == 'push' %}
            Commit: ${{ github.event.head_commit.message }}
            Link:   ${{ github.event.head_commit.url }}
            {% else %}
            Issue:  #${{ github.event.issue.number }} — ${{ github.event.issue.title }}
            Link:   ${{ github.event.issue.html_url }}
            Comment: ${{ github.event.comment.body || 'N/A' }}
            {% endif %}
